Contact-Page-Branch:
mercymugambi/set-up-mobile-first-portfolio pull request #3
Opened 2023-02-21 14:01 UTC by tsheporamantso

## On this milestone:-

- Ensured there are no linter errors
- Add contact form section
- Layout HTML elements with FlexBox
- Adhered to GitHub flow and also adhered to HTML and CSS best practices

2023-02-21 17:32 UTC, Shisui6 requested changes
Hi @tsheporamantso and @mercymugambi , 

# Requires Changes 🍀
You have done a great job so far!
Your design is good 🖼️, and your code follows best practices. However, there are a few issues that you still need to work on.

## Highlights
 - Good use of flexbox ✅
 - HTML validations done correctly ✅
 - Formspree service used ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 17:32 UTC, Shisui6 commented on style.css
Your stylesheet is currently not linked to your HTML so none of your styles are being applied. Please check the path supplied to the link tag in your HTML's head tag and ensure its correct🙏

When doing so try your best to match the figma design as much as possible. Dont to style the button interactions😎

2023-02-21 17:32 UTC, Shisui6 commented on index.html
> +          </li>
[Optional] There is no need to wrap your form input elements in `<ul>` and `<li>` tags since they are not list items. I strongly suggest you refactor this to make your code clean🫡

2023-02-21 19:31 UTC, mercymugambi commented
Hallo Reviewer,

- @Shisui6 As my previous reviewer, I appreciate the comments given. However, for every projects given theres also some guiding material. Like for the case with forms, We had a microverse document that acted as guide and that how i ended with wraping for <ul> <li>tags. 
- Also, about the stylesheet not being linked to my html file, i think you can clear the browser cashe as from my end it is displaying well as shown on the image.
![mobile](https://user-images.githubusercontent.com/48310207/220440507-49e4fbaf-8d1f-44f3-87f8-836aba9d2eca.PNG)

Thank you!

2023-02-21 19:55 UTC, vickymarz requested changes
Hi @tsheporamantso, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 19:55 UTC, vickymarz commented on index.html
> +    <section class="contact-page-container">
- [ ] Your stylesheet is truly not displaying as specified by the previous reviewer. YOu should add a dot before the relative path of your style URL to display the styles 👍🏽 

![image](https://user-images.githubusercontent.com/63473584/220445074-9225f47c-d989-4590-ba65-91d7318cbdc9.png)

2023-02-21 20:01 UTC, Shisui6 commented
Hello @mercymugambi,

When linking stylesheets in HTML, its important to specify the relative path to the file. This is usually done by adding a `.` before the path to your file. This way, the browser knows exactly where to look for the file regardless of which computer is looking at it. I suggest you update your link to your stylesheet to look like `./style.css` so your styles will show on any platform

2023-02-22 08:45 UTC, mercymugambi commented
@Shisui6 @vickymarz
Relative path added to the css path as requested.

Thank you

2023-02-22 09:00 UTC, Olamarx approved these changes
Hi @tsheporamantso,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/1O1UUSESiuGSi1VdT6/giphy.gif"/>
## Highlights
- Form tag ✔️ 
- input attributes ✔️ 
- correct use of formspree ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 09:18 UTC, merged